version: '3.8'
services:
  node-app:
    build: .
    ports:
      - '3200:3200'
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - PORT=3200
    # env_file:
    #   - ./.env
