version: '3.8'
services:
  nginx:
    image: nginx:stable-alpine
    ports:
      - '3200:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - node-app

  node-app:
    build: .
    environment:
      - PORT=3200
    depends_on:
      - mongo
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=michael
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - mongo-db:/data/db
  redis:
    image: redis

volumes:
  mongo-db:
