version: '3.8'
services:
  nginx:
    ports:
      - '3200:80'

  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=michael
      - MONGO_PASSWORD=password
      - SESSION_SECRET=secret
    command: yarn dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=michael
      - MONGO_INITDB_ROOT_PASSWORD=password
